"""empty message

Revision ID: 4ac5caf7e821
Revises: 6d6e26f5bd10
Create Date: 2024-03-19 12:42:31.831668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac5caf7e821'
down_revision = '6d6e26f5bd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers_table', schema=None) as batch_op:
        batch_op.alter_column('is_certified',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers_table', schema=None) as batch_op:
        batch_op.alter_column('is_certified',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
