"""empty message

Revision ID: 6d6e26f5bd10
Revises: cc432e1ed490
Create Date: 2024-03-18 10:43:42.928480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6e26f5bd10'
down_revision = 'cc432e1ed490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))

    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_matches_table_message_id_messages_table', type_='foreignkey')
        batch_op.drop_column('message_id')

    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_table_match_id_matches_table'), 'matches_table', ['match_id'], ['id'])

    with op.batch_alter_table('trainers_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers_table', schema=None) as batch_op:
        batch_op.drop_column('city')

    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_table_match_id_matches_table'), type_='foreignkey')
        batch_op.drop_column('match_id')

    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_matches_table_message_id_messages_table', 'messages_table', ['message_id'], ['id'])

    with op.batch_alter_table('clients_table', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
