"""empty message

Revision ID: 73f7db8e5d89
Revises: b22dcbb0e127
Create Date: 2024-03-15 12:01:23.594056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f7db8e5d89'
down_revision = 'b22dcbb0e127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['matches_table.client_id'], name=op.f('fk_messages_table_client_id_matches_table')),
    sa.ForeignKeyConstraint(['trainer_id'], ['matches_table.trainer_id'], name=op.f('fk_messages_table_trainer_id_matches_table')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_matches_table_message_id_messages_table'), 'messages_table', ['message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_matches_table_message_id_messages_table'), type_='foreignkey')
        batch_op.drop_column('message_id')

    op.drop_table('messages_table')
    # ### end Alembic commands ###
