"""empty message

Revision ID: 9bc6a8a18d01
Revises: 73f7db8e5d89
Create Date: 2024-03-15 12:02:16.847980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc6a8a18d01'
down_revision = '73f7db8e5d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_table_client_id_matches_table', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_table_trainer_id_matches_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_table_trainer_id_trainers_table'), 'trainers_table', ['trainer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_table_client_id_clients_table'), 'clients_table', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_table_client_id_clients_table'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_table_trainer_id_trainers_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_table_trainer_id_matches_table', 'matches_table', ['trainer_id'], ['trainer_id'])
        batch_op.create_foreign_key('fk_messages_table_client_id_matches_table', 'matches_table', ['client_id'], ['client_id'])

    # ### end Alembic commands ###
