"""empty message

Revision ID: b22dcbb0e127
Revises: 
Create Date: 2024-03-14 11:31:53.789955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22dcbb0e127'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('dob_month', sa.Integer(), nullable=False),
    sa.Column('dob_day', sa.Integer(), nullable=False),
    sa.Column('dob_year', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('img1', sa.String(), nullable=True),
    sa.Column('img2', sa.String(), nullable=True),
    sa.Column('img3', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trainers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('dob_month', sa.Integer(), nullable=False),
    sa.Column('dob_day', sa.Integer(), nullable=False),
    sa.Column('dob_year', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('img1', sa.String(), nullable=True),
    sa.Column('img2', sa.String(), nullable=True),
    sa.Column('img3', sa.String(), nullable=True),
    sa.Column('is_certified', sa.Boolean(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('matches_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_table.id'], name=op.f('fk_matches_table_client_id_clients_table')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers_table.id'], name=op.f('fk_matches_table_trainer_id_trainers_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches_table')
    op.drop_table('trainers_table')
    op.drop_table('clients_table')
    # ### end Alembic commands ###
