"""empty message

Revision ID: cc432e1ed490
Revises: 9bc6a8a18d01
Create Date: 2024-03-16 12:54:51.022117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc432e1ed490'
down_revision = '9bc6a8a18d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialty_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialty')
    )
    op.create_table('trainer_specialty_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty_table.id'], name=op.f('fk_trainer_specialty_table_specialty_id_specialty_table')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers_table.id'], name=op.f('fk_trainer_specialty_table_trainer_id_trainers_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_specialty_table')
    op.drop_table('specialty_table')
    # ### end Alembic commands ###
